---
- name: setup system 
  hosts: gerrit_install_targets
  sudo: yes
  gather_facts: no
  tasks:
  - name: install pkg
    yum: pkg={{item}} state=installed
    with_items:
    - git-core
    - ant
    - postgresql
  - name: gerritユーザーを追加
    user: name={{gerrit_user}} system=yes state=present move_home=yes home=/var/lib/{{gerrit_user}}

