---
- name: install gerrit dependencies
  hosts: gerrit_install_targets
  sudo: yes
  gather_facts: no
  tasks:
  - name: install pkg
    yum: pkg={{item}} state=installed
    with_items:
    - git-core
    - ant
    - postgresql

